- name: Install and run Docker on machines
  hosts: web
  become: true
  become_user: root

  tasks:

    - name: Upgrade all packages on servers
      shell: dnf upgrade -y

    - name: Set up docker repository
      shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install the latest version of Docker Engine and containerd
      shell: dnf install -y docker-ce docker-ce-cli containerd.io

    - name: Add the current user to the docker group
      shell: usermod -aG docker {{ ansible_env.USER }}

    - name: Start and enable docker service
      shell: systemctl enable --now docker

    - name: Pull and run Docker container from web-image image
      shell: |
        docker pull mohamedfathy23/web-app
        docker run -d -p 5000:5000 --name web-app mohamedfathy23/web-app

